version: '3' # 表示该 Docker-Compose 文件使用的是 Version 3 file
services:
  order: # 指定服务名称
    build: .  # 指定 Dockerfile 所在路径
    container_name: docker-order-sys
    ports: # 指定端口映射
      - "8991:8080"
      - "45006:5005"
  pay: # 指定服务名称
    build: .  # 指定 Dockerfile 所在路径
    container_name: docker-pay-sys
    ports: # 指定端口映射
      - "8992:8080"
      - "45007:5005"